Global:
  use_gpu: true
  epoch_num: 100
  log_smooth_window: 20
  print_batch_step: 20
  save_model_dir: ./tests
  save_epoch_step: 120
  # evaluation is run every 2000 iterations after the 3000th iteration
  eval_batch_step: [20, 4000]
  cal_metric_during_train: False
  pretrained_model: ../../input/det-r18-v253/db_r18_v2.5.3/best_accuracy
  checkpoints: 
  save_inference_dir:
  use_visualdl: False
  visualdl_file_name: 
  infer_img: /home/nhhviet/ftech.ai/data/ekyc/private_test/images/Task 2/
  save_res_path: ./output/det_db/predicts_db.txt

Architecture:
  model_type: det
  algorithm: DB
  Transform:
  Backbone:
    name: ResNet
    layers: 18
    disable_se: True
  Neck:
    name: DBFPN
    out_channels: 256
  Head:
    name: DBHead
    k: 50

Loss:
  name: DBLoss
  balance_loss: true
  main_loss_type: DiceLoss
  alpha: 5
  beta: 10
  ohem_ratio: 3

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.0001
    warmup_epoch: 2
  regularizer:
    name: 'L2'
    factor: 0

PostProcess:
  name: DBPostProcess
  thresh: 0.80
  box_thresh: 0.85
  max_candidates: 1000
  unclip_ratio: 2.5
  use_dilation: True
  score_mode: slow

Metric:
  name: DetMetric
  main_indicator: recall

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ../../input/dataset-v265/dataset_v2.6.5/
    label_file_list:
      - ../../input/dataset-v265/dataset_v2.6.5/train.txt
    ratio_list: [1.0]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - DetLabelEncode: # Class handling label
      - IaaAugment:
          augmenter_args:
            - { 'type': Fliplr, 'args': { 'p': 0.25 } }
            - { 'type': Affine, 'args': { 'rotate': [-10, 10] } }
            - { 'type': Resize, 'args': { 'size': [0.8, 1.5] } }
            - { 'type': MotionBlur, 'args': { 'k': [5, 11], 'angle': [0, 360] } }
            - { 'type': GaussianBlur, 'args': { 'sigma': [0.5, 2.5] } }
            - { 'type': GammaContrast, 'args': { 'gamma': [0.5, 2.5] , 'per_channel': True } }
      - EastRandomCropData:
          size: [960, 960]
          max_tries: 50
          keep_ratio: true
      - MakeBorderMap:
          shrink_ratio: 0.34
          thresh_min: 0.3
          thresh_max: 0.7
      - MakeShrinkMap:
          shrink_ratio: 0.34
          min_text_size: 8
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'threshold_map', 'threshold_mask', 'shrink_map', 'shrink_mask'] # the order of the dataloader list
  loader:
    shuffle: True
    drop_last: False
    batch_size_per_card: 12
    num_workers: 6

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ../../input/private-test-new-3/private_test_new_3/
    label_file_list:
      - ../../input/private-test-new-3/private_test_new_3/annotations.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - DetLabelEncode: # Class handling label
      - DetResizeForTest:
#           image_shape: [736, 1280]
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'shape', 'polys', 'ignore_tags']
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 1 # must be 1
    num_workers: 6
