Global:
  use_gpu: true
  epoch_num: 1200
  log_smooth_window: 20
  print_batch_step: 2
  save_model_dir: ./output/det/v2.3.0
  save_epoch_step: 1200
  # evaluation is run every 2000 iterations after the 3000th iteration
  eval_batch_step: [20, 2000]
  cal_metric_during_train: False
  pretrained_model:
  checkpoints: /home/sonnda/paddle-ocr/output/det/db_r18_v2.5.3/best_accuracy
  save_inference_dir:
  use_visualdl: True
  visualdl_file_name: vdlrecords
  infer_img: /home/nhhviet/ftech.ai/data/ekyc/private_test_v2/images/ROI_front_1009246.jpg
  save_res_path: ./test_result/det_db/predicts_db.txt

Architecture:
  model_type: det
  algorithm: DB
  Transform:
  Backbone:
    name: ResNet
    layers: 18
    disable_se: True
  Neck:
    name: DBFPN
    out_channels: 256
  Head:
    name: DBHead
    k: 50

Loss:
  name: DBLoss
  balance_loss: true
  main_loss_type: DiceLoss
  alpha: 5
  beta: 10
  ohem_ratio: 3

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 2
  regularizer:
    name: 'L2'
    factor: 0

PostProcess:
  name: DBPostProcess
  thresh: 0.8
  box_thresh: 0.85
  max_candidates: 1000
  unclip_ratio: 3
  use_dilation: True
  score_mode: slow

Metric:
  name: DetMetricEvaluation
  main_indicator: hmean
  iou_values: [0.5, 0.55,  0.6, 0.65, 0.7, 0.75, 0.8]

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /home/nhhviet/ftech.ai/data/ekyc/private_test
    label_file_list:
      - /home/nhhviet/ftech.ai/data/ekyc/private_test/annotations_normal.txt
    ratio_list: [1.0]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - DetLabelEncode: # Class handling label
      - IaaAugment:
          augmenter_args:
            - { 'type': Fliplr, 'args': { 'p': 0.5 } }
            - { 'type': Affine, 'args': { 'rotate': [-10, 10] } }
            - { 'type': Resize, 'args': { 'size': [0.5, 3] } }
      - EastRandomCropData:
          size: [960, 960]
          max_tries: 50
          keep_ratio: true
      - MakeBorderMap:
          shrink_ratio: 0.4
          thresh_min: 0.3
          thresh_max: 0.7
      - MakeShrinkMap:
          shrink_ratio: 0.4
          min_text_size: 8
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'threshold_map', 'threshold_mask', 'shrink_map', 'shrink_mask'] # the order of the dataloader list
  loader:
    shuffle: True
    drop_last: False
    batch_size_per_card: 1
    num_workers: 1

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /home/sonnda/data/ekyc/private_test_new_3
    label_file_list:
      - /home/sonnda/data/ekyc/private_test_new_3/annotations.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - DetLabelEncode: # Class handling label
      - DetResizeForTest:
#           image_shape: [736, 1280]
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'shape', 'polys', 'ignore_tags', 'texts', 'kie_classes']
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 1 # must be 1
    num_workers: 1